### ISSUE TITLE
Flex to FlexJS: What's up with SkinnableComponent (or skinning generally) in FlexJS?

### ISSUE THREAD

**Issue by neminovno** [ok-at-github/flexjs-docs#2]
Please add the answer in wiki.

**Comment by piotrzarzycki21** [comment]
Hi @neminovno ,

In FlexJS there is no 100% equivalent to skins, however I see two possibilities.
1) CSS - you can stylize your components by css almost as it is in HTML. Some components already have default theme for example all MDL stuff
2) Beads - That's small classes which adding some functionality to components - particular it means that you can have as part of that class code which change appearance of your component. A bit more on wiki page [1]

We are working peace by peace on this documentation, so hopefully you will find soon more answers to your questions.

[1] https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=71013028

Thanks,
Piotr

**Comment by neminovno** [comment]
Hi @piotrzarzycki21 , thanks, I'll be watching ;)
